{{- $replicas := .Values.replicaCount | int -}}
{{- $name := .Values.flix.instanceName  }}
{{- $domain := .Values.domainName }}
{{- $edns := .Values.externalDNS.enabled }}
{{- $ednt := .Values.externalDNS.ttl | int | quote }}
{{- $anlb := .Values.awsNLB.enabled }}
{{- $cano := .Values.customAnnotations.enabled }}
{{- $cans := .Values.customAnnotations.annotations }}
{{- $port := .Values.service.port }}
{{- range $i,$e := until $replicas }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- if $edns }}
    external-dns.alpha.kubernetes.io/hostname: {{ $name }}-{{ $i }}.{{ $domain }}
    external-dns.alpha.kubernetes.io/ttl: {{ $ednt }}
  {{- end }}
  {{- if $anlb }}
    service.beta.kubernetes.io/aws-load-balancer-name: {{ $name }}-{{ $i }}-svc
  {{- end }}
  {{- if $cano }}
{{ toYaml $cans | indent 4 }}
  {{- end }}
  name: {{ $name }}-{{ $i }}-svc
  labels:
    statefulset.kubernetes.io/pod-name: {{ $name }}-{{ $i }}
spec:
  type: LoadBalancer
  ports:
    - name: http-port
      port: {{ $port }}
      protocol: TCP
      targetPort: {{ $port }}
    - name: file-port
      port: 9091
      protocol: TCP
      targetPort: 9091
    - name: rpc-port
      port: 9876
      protocol: TCP
      targetPort: 9876
    - name: rpn-port
      port: 9877
      protocol: TCP
      targetPort: 9877
  selector:
    app: flix-server
    statefulset.kubernetes.io/pod-name: {{ $name }}-{{ $i }}
{{- end }}
